#!/usr/bin/env perl
use 5.016;
use warnings;
use autodie;

my @dirs;

opendir my $dh, '.';
while (readdir $dh) {
    push @dirs, $_ if -d && !/^\./;
}

system { "/usr/bin/stow" } ("stow", "-Rv", @dirs);
