(require 'ert)

(defun custom-variable-default-value (var)
  (eval (car (get var 'standard-value))))

(ert-deftest test-grep-files-aliases ()
  (should (equal (custom-variable-default-value 'grep-files-aliases)
                 '(("all" .   "* .[!.]* ..?*")
                   ("el" .    "*.el")
                   ("ch" .    "*.[ch]")
                   ("c" .     "*.c")
                   ("cc" .    "*.cc *.cxx *.cpp *.C *.CC *.c++")
                   ("cchh" .  "*.cc *.[ch]xx *.[ch]pp *.[CHh] *.CC *.HH *.[ch]++")
                   ("hh" .    "*.hxx *.hpp *.[Hh] *.HH *.h++")
                   ("h" .     "*.h")
                   ("l" .     "[Cc]hange[Ll]og*")
                   ("m" .     "[Mm]akefile*")
                   ("tex" .   "*.tex")
                   ("texi" .  "*.texi")
                   ("asm" .   "*.[sS]")))))

(provide 'custom-test)
